from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='AppSettings',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
            ('singleton',models.BooleanField(default=True,editable=False,unique=True)),('company_monthly_signalhire_limit',models.PositiveIntegerField(default=2000)),('default_requirement_signalhire_limit',models.PositiveIntegerField(default=10)),('auto_match_threshold',models.PositiveIntegerField(default=90)),('possible_match_threshold',models.PositiveIntegerField(default=70)),('signalhire_api_key_cipher',models.TextField(blank=True)),('signalhire_mode',models.CharField(choices=[('sync','Sync'),('async','Async')],default='sync',max_length=10)),('signalhire_callback_secret',models.CharField(blank=True,max_length=120)),('applicant_sync_lookback_days',models.PositiveIntegerField(default=365)),
        ]),
        migrations.CreateModel(name='BackgroundTask',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('task_type',models.CharField(max_length=80)),('payload',models.JSONField(blank=True,default=dict)),('status',models.CharField(choices=[('PENDING','Pending'),('RUNNING','Running'),('DONE','Done'),('FAILED','Failed')],db_index=True,default='PENDING',max_length=20)),('attempts',models.PositiveIntegerField(default=0)),('error',models.TextField(blank=True)),('available_at',models.DateTimeField(default=django.utils.timezone.now)),('locked_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),
        ]),
        migrations.CreateModel(name='CeipalOrganization',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('code',models.SlugField(max_length=30,unique=True,help_text='Example: us or india')),('base_url',models.URLField(default='https://api.ceipal.com')),('api_version',models.CharField(default='v1',max_length=10)),('api_email',models.EmailField(max_length=254)),('api_password_cipher',models.TextField(blank=True)),('api_key_cipher',models.TextField(blank=True)),('active',models.BooleanField(default=True)),('auth_path',models.CharField(default='/v1/createAuthtoken',max_length=200)),('jobs_path',models.CharField(default='/v1/getJobPostingsList',max_length=200)),('applicants_path',models.CharField(default='/v1/getApplicantsList',max_length=200)),('applicant_exact_search_path',models.CharField(blank=True,help_text='Optional CEIPAL V2/Custom endpoint that supports exact email/mobile filters. If blank, the local synchronized Applicant index is used.',max_length=200)),('submissions_path',models.CharField(default='/v1/getSubmissionsList',max_length=200)),('apply_without_registration_path',models.CharField(default='/v1/applyJobWithOutRegistration',max_length=200)),('create_applicant_path',models.CharField(default='/v1/createApplicant',max_length=200)),('update_applicant_path',models.CharField(blank=True,help_text='Your CEIPAL V2/Custom PATCH endpoint for an existing Applicant.',max_length=200)),('secondary_document_path',models.CharField(blank=True,help_text='Your CEIPAL endpoint for adding a secondary Applicant document without replacing the primary resume.',max_length=200)),('existing_tag_path',models.CharField(blank=True,help_text='Preferred endpoint to tag an existing Applicant to a job using job_id + job_seeker_id. Leave blank to use Apply Without Registration only if sandbox-tested.',max_length=200)),('use_apply_for_existing_tagging',models.BooleanField(default=False,help_text='Enable only after confirming CEIPAL reuses an existing Applicant instead of creating a duplicate.')),('linkedin_field_name',models.CharField(default='linkedInProfileUrl',max_length=100)),('document_field_name',models.CharField(default='document_fields.1',max_length=100)),('country_default',models.CharField(blank=True,max_length=20)),('state_default',models.CharField(blank=True,max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),
        ]),
        migrations.CreateModel(name='UserProfile',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('monthly_signalhire_limit',models.PositiveIntegerField(default=100)),('is_manager',models.BooleanField(default=False)),('ceipal_orgs',models.ManyToManyField(blank=True,related_name='user_profiles',to='hub.ceipalorganization')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user')),
        ]),
        migrations.CreateModel(name='Requirement',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('entered_req_id',models.CharField(max_length=120)),('ceipal_job_id',models.CharField(max_length=500)),('job_title',models.CharField(blank=True,max_length=500)),('client_name',models.CharField(blank=True,max_length=500)),('location',models.CharField(blank=True,max_length=500)),('job_description',models.TextField(blank=True)),('skills',models.TextField(blank=True)),('signalhire_limit_override',models.PositiveIntegerField(blank=True,null=True)),('raw_data',models.JSONField(blank=True,default=dict)),('fetched_at',models.DateTimeField(default=django.utils.timezone.now)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='requirements_worked',to='auth.user')),('org',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='hub.ceipalorganization')),
        ]),
        migrations.CreateModel(name='ApplicantIndex',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('ceipal_applicant_id',models.CharField(max_length=500)),('applicant_number',models.CharField(blank=True,max_length=100)),('first_name',models.CharField(blank=True,max_length=200)),('last_name',models.CharField(blank=True,max_length=200)),('full_name',models.CharField(blank=True,db_index=True,max_length=500)),('email',models.EmailField(blank=True,db_index=True,max_length=254)),('alt_email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,db_index=True,max_length=100)),('city',models.CharField(blank=True,max_length=200)),('state',models.CharField(blank=True,max_length=200)),('country',models.CharField(blank=True,max_length=200)),('job_title',models.CharField(blank=True,max_length=500)),('skills',models.TextField(blank=True)),('linkedin_url',models.URLField(blank=True,db_index=True,max_length=1000)),('linkedin_normalized',models.CharField(blank=True,db_index=True,max_length=1000)),('phone_normalized',models.CharField(blank=True,db_index=True,max_length=32)),('resume_path',models.TextField(blank=True)),('raw_data',models.JSONField(blank=True,default=dict)),('ceipal_modified',models.DateTimeField(blank=True,null=True)),('synced_at',models.DateTimeField(auto_now=True)),('org',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='applicant_index',to='hub.ceipalorganization')),
        ]),
        migrations.CreateModel(name='ImportBatch',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('filename',models.CharField(max_length=500)),('row_count',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('requirement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='batches',to='hub.requirement')),('uploaded_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user')),
        ]),
        migrations.CreateModel(name='ImportCandidate',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('row_number',models.PositiveIntegerField()),('name',models.CharField(max_length=500)),('linkedin_url',models.URLField(blank=True,max_length=1000)),('location',models.CharField(blank=True,max_length=500)),('skills',models.TextField(blank=True)),('status',models.CharField(choices=[('NEW','New'),('EXISTING','Existing'),('POSSIBLE','Possible Match'),('READY','Ready for SignalHire'),('PENDING','SignalHire Pending'),('COMPLETE','Complete'),('FAILED','Failed'),('SKIPPED','Skipped')],default='NEW',max_length=20)),('match_score',models.PositiveIntegerField(default=0)),('job_fit_score',models.PositiveIntegerField(default=0)),('selected',models.BooleanField(default=False)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=100)),('signalhire_request_id',models.CharField(blank=True,max_length=100)),('signalhire_status',models.CharField(blank=True,max_length=50)),('signalhire_payload',models.JSONField(blank=True,default=dict)),('ceipal_applicant_id',models.CharField(blank=True,max_length=500)),('ceipal_submission_id',models.CharField(blank=True,max_length=500)),('created_new_applicant',models.BooleanField(default=False)),('profile_pdf',models.FileField(blank=True,upload_to='candidate_profiles/%Y/%m/')),('error_message',models.TextField(blank=True)),('processing_state',models.CharField(default='NEW',max_length=50)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('batch',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='candidates',to='hub.importbatch')),('matched_applicant',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='hub.applicantindex')),
        ]),
        migrations.CreateModel(name='SignalHireUsage',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('month',models.DateField(db_index=True)),('status',models.CharField(choices=[('RESERVED','Reserved'),('CONSUMED','Consumed'),('RELEASED','Released'),('FAILED','Failed')],max_length=20)),('credits',models.PositiveIntegerField(default=1)),('signalhire_remaining',models.IntegerField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('candidate',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='credit_events',to='hub.importcandidate')),('requirement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='signalhire_usage',to='hub.requirement')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user')),
        ]),
        migrations.CreateModel(name='AuditLog',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('details',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('candidate',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='hub.importcandidate')),('requirement',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='hub.requirement')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user')),
            ],options={'ordering':['-created_at']}),
        migrations.AddConstraint(model_name='requirement',constraint=models.UniqueConstraint(fields=('org','ceipal_job_id'),name='unique_requirement_per_org')),
        migrations.AddConstraint(model_name='applicantindex',constraint=models.UniqueConstraint(fields=('org','ceipal_applicant_id'),name='unique_applicant_per_org')),
        migrations.AddConstraint(model_name='importcandidate',constraint=models.UniqueConstraint(fields=('batch','row_number'),name='unique_row_per_batch')),
        migrations.AddIndex(model_name='signalhireusage',index=models.Index(fields=['month','status'],name='hub_signalh_month_27da4c_idx')),
        migrations.AddIndex(model_name='signalhireusage',index=models.Index(fields=['requirement','status'],name='hub_signalh_require_82a9f7_idx')),
        migrations.AddIndex(model_name='signalhireusage',index=models.Index(fields=['user','month','status'],name='hub_signalh_user_id_861029_idx')),
    ]
